### ISSUE TITLE
Form Preview + FE fixes

### ISSUE THREAD

**Issue by therealsharath** [GTBitsOfGood/recruitment-portal#2]
- [x]  Highlight radio button cards when empty & required
- [x]  Add review page
    - Applicants don’t get to review their apps after they’ve filled it out
- [x]  Enable light or dark mode based on system setting
- [x]  Make hover cards have hand-pointer cursor
- [x] Add word limit + counter

### Stretch
- [ ]  Animations
