### ISSUE TITLE
Notion Fixes

### ISSUE THREAD

**Issue by therealsharath** [GTBitsOfGood/recruitment-portal#3]
- [x] Error handling from Notion
- [ ] Templating Notion Review page
- [ ] Create script to compile and tabulate scores in Notion
